version: '3'

services:
  webapp:
    image: my-webapp-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:mydatabase;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      # - REDIS_HOST=redis
    depends_on:
      - db
    ports:
      - "8080:8080"
    entrypoint: ["/entrypoint.sh"]

  db:
    image: oscarfonts/h2:latest
    environment:
      - H2_OPTIONS=-ifNotExists
    ports:
      - "5433:9092"

#  redis:
#    image: "redis:latest"
#    ports:
#      - "6380:6379"
